#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: r1
#          uri: lb://USERMS
#          predicates:
#            - Path= /users/**
#        - id: r2
#          uri: lb://ORGANISATIONMS
#          predicates:
#            - Path= /organistions/**


spring:
  application:
    name: GateWay
  config:
    import: optional:configserver:http://localhost:8090
server:
  port: 8083